- name: Enable Systemd-Resolved service
  ansible.builtin.systemd_service:
    name: systemd-resolved.service
    state: started
    enabled: yes

- name: Link Systemd-Resolved Stub
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: link
    src: /run/systemd/resolve/stub-resolv.conf

- name: Enable DNS server and security features
  community.general.ini_file:
    path: /etc/systemd/resolved.conf.d/dns_over_tls.conf
    group: root
    mode: "644"
    no_extra_spaces: true
    option: "{{ item.option }}"
    owner: root
    section: "Resolve"
    value: "{{ item.value }}"
  loop:
    - {
        option: "DNS",
        value: "1.1.1.1#cloudflare-dns.com 9.9.9.9#dns.quad9.net",
      }
    - { option: "DNSOverTLS", value: "yes" }
    - { option: "DNSSEC", value: "yes" }
    - { option: "Domains", value: "~." }
  loop_control:
    label: "{{ item.option }}"
