# basic
dir=${HOME}/Downloads
max-concurrent-downloads=4
check-integrity=true
continue=true

# HTTP
enable-http-pipelining=true
max-tries=0
min-split-size=10M
retry-wait=30
split=16
timeout=600

# BitTorrent
bt-force-encryption=true
listen-port=51413
dht-listen-port=51413
seed-ratio=3.0

# advance
always-resume=true
disk-cache=32M
disable-ipv6=true
file-allocation=falloc

# RPC
#rpc-listen-all=true
#rpc-secret=aria2rpc
