auto-key-retrieve
no-greeting
keyserver hkps://keyserver.ubuntu.com
keyserver-options timeout=10
keyserver-options import-clean
keyserver-options no-self-sigs-only
use-agent

# Mozilla InfoSec
personal-digest-preferences SHA512 SHA384
cert-digest-algo SHA256
default-preference-list SHA512 SHA384 AES256 ZLIB BZIP2 ZIP Uncompressed
keyid-format 0xlong
