- name: Link static config files
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"
    force: true
  # yamllint disable rule:indentation
  loop:
    - {
        name: "Xonsh config directory",
        src: "{{ playbook_dir }}/files/home/config/xonsh",
        path: "{{ home }}/.config/xonsh/rc.d",
      }
  # yamllint enable rule:indentation
  loop_control:
    label: "Linking {{ item.name }}"
