- name: Get latest release
  community.general.github_release:
    user: "{{ github_owner }}"
    repo: "{{ github_repo }}"
    action: latest_release
  register: latest_release

- name: Ensure fonts directory exists
  ansible.builtin.file:
    path: "/home/{{ user }}/.local/share/fonts/{{ github_repo }}"
    state: directory
    mode: "u=rwx,go=rx"

- name: Download and extract the latest release archive
  ansible.builtin.unarchive:
    src: "https://github.com/{{ github_owner }}/{{ github_repo }}/releases/download/{{ latest_release.tag }}/{{ asset_name }}"
    dest: "/home/{{ user }}/.local/share/fonts/{{ github_repo }}"
    remote_src: true
