[Build]
CacheDirectory=mkosi.cache
Incremental=true

[Content]
Packages=tailscale

[Distribution]
Distribution=arch
Release=rolling

[Output]
# CompressOutput=true
Format=portable
OutputDirectory=mkosi.output
Output=tailscaled
