- name: illumi
  hosts: localhost
  become: true
  vars:
    user: shubms
    sub_id_start: 1048576
    sub_id_count: 1048576

  tasks:
    - name: Configure containers
      ansible.builtin.include_tasks: ../tasks/system/10-containers.yaml
    - name: Configure DNS and resolve.conf
      ansible.builtin.include_tasks: ../tasks/system/10-networking.yaml
    - name: Configure KDE Linux
      ansible.builtin.include_tasks: ../tasks/system/20-kdelinux.yaml
