[Config]
Dependencies=base

[Content]
BaseTrees=%O/base
Packages=vivaldi

[Output]
# CompressOutput=true
Format=sysext
Overlay=yes
Output=vivaldi

# [Validation]
# Verity=signed
# VerityKey=priv.key
# VerityCertificate=cert.crt
